# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake

  - repo: https://github.com/ambv/black
    rev: 24.1.1
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-builtins>=2.1.0
          - flake8-import-order==0.18.2
          - flake8-bugbear>=23.12
          - flake8-comprehensions>=3.10.1
          - flake8-isort>=6
          - flake8-simplify>=0.19.3
          - flake8-eradicate>=1
        args:
          - --per-file-ignores=kpconv_torch/utils/visualizer.py:B023

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args: [--fail-under=8]
        files: \.py
        exclude: .pylintrc

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
